import "./globals.css";


export const metadata = {
  title: "Week 10",
  description: "Generated by Ev's hands",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
