import "./globals.css";
import Nav from "@/components/Global/Nav";

export const metadata = {
  title: "Week 11: Layouts and File Upload Conversions",
  description: "Generated by create next app (and Ev's awesome coding skillz)",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
